[package]
name = "server"
version.workspace = true
edition.workspace = true

[dependencies]
axum = "0.8.1"
serde ={ version = "1.0.217", features = ["derive"] }
tokio = { version = "1.43.0", features = ["full"] }
prover = { path = "../prover" }
tower-http={version = "0.6.2", features = ["cors"]}
