[package]
name = "prover"
version.workspace = true
edition.workspace = true

[dependencies]
wasm-bindgen = "0.2.100"
stwo-prover = {git = "https://github.com/starkware-libs/stwo.git"}
itertools = "0.12.0"
num-traits = "0.2.17"
serde_json = "1.0.64"

# [lib]
# crate-type = ["cdylib"]
